### ISSUE TITLE
Extend the user schema entity with gender and weight

### ISSUE THREAD

**Issue by Tschonti** [kir-dev/BeAlcoholic#23]
To estimate the blood alcohol level of a person, we'll need their gender and weight. We can't get this info from AuthSch, so the user must add it to their profile.
Subtasks:

- [x] add gender(male/female) and weight (number, kg) fields to the prisma schema. Both fields should be nullable, since when the user first logs in, we won't know these details
- [x] modify the user entity, add these same fields
- [x] the weight of the users shouldn't be exposed, so edit the user findOne and findAll methods to exclude that field from the result.
- [x] create an endpoint where these details can be edited on a user. `PATCH /users/:userId`. Create a DTO with the two fields and edit the data on the user record in the service

**Comment by cpwallah** [comment]
hi can i work on this @Tschonti

**Comment by Tschonti** [comment]
Sorry, these issues are to be developed by the members of our team
