### ISSUE TITLE
Connect the user model to the Event model

### ISSUE THREAD

**Issue by Tschonti** [kir-dev/BeAlcoholic#28]
Only signed-in users should be able to create events. With every event created, we should save who created that event.

Subtasks:
- [x] modify the schema to connect the user and event tables with many-to-one connection (the lines are there but as a comment)
- [x] update the Event entity class with the ownerId field
- [x] enforce authentication on the create event endpoint
- [x] save the id of the signed-in user when creating an event

[Example endpoint with authentication](https://github.com/kir-dev/passport-authsch?tab=readme-ov-file#example-endpoint-using-the-jwt-authentication)

**Comment by abhedanil** [comment]
Which language /library are you using at backend ?

**Comment by abhedanil** [comment]
I would like to work on this , can i get started?

**Comment by Tschonti** [comment]
no sorry, these issues are to be developed by the members of our team

**Comment by abhedanil** [comment]
Thanks
