### ISSUE TITLE
Create User controller, DTOs and service

### ISSUE THREAD

**Issue by Tschonti** [kir-dev/BeAlcoholic#9]
Since authentication (to be implemented later) will be responsible for creating users, this resource won't do too much for now.
The controller should have the following endpoints: 
GET user by id
GET all users
Delete user by id

Create the user entity dto, no need for the create user and update user. Implement the necessary methods in the service

We will extend this resource once users are connected to drink actions

**Comment by Hussain15527** [comment]
please assign me this.

**Comment by Tschonti** [comment]
Sorry, these issues are to be developed by the members of our team
